framework:
    default_locale: 'es'
    translator:
        paths:
            #- '%kernel.project_dir%/translations'
            - '%kernel.project_dir%/src/CorredoresRioja/Resources/translations'
        fallbacks:
            - 'es'
