#index:
#    path: /
#    controller: App\Controller\DefaultController::index

principal:
    resource: '../src/CorredoresRioja/Resources/routing/routes.yaml'
    

corredores:
    resource: '../src/CorredoresRioja/Resources/routing/routesCorredores.yaml'
    prefix: 
        en: /runners
        es: /corredores
    
organizaciones:
    resource: '../src/CorredoresRioja/Resources/routing/routesOrganizaciones.yaml'
    prefix: /organizaciones